
import com.sun.corba.se.impl.oa.poa.Policies;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Polygon;
import java.util.ArrayList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDesenho.java
 *
 * Created on 19/08/2011, 20:59:13
 */
/**
 *
 * @author manchini
 */
public class JDesenho extends javax.swing.JFrame {

    /** Creates new form JDesenho */
    ArrayList<Point> pontos = new ArrayList<Point>();

    public JDesenho() {
        initComponents();
    }

    private void desenhaQuadrado() {
        if (pontos.size() > 1) {
            Graphics g = this.getGraphics();
            int[] xs = new int[pontos.size()];
            int[] ys = new int[pontos.size()];
            for (int i = 0; i < pontos.size(); i++) {
                Point point = pontos.get(i);
                xs[i] = new Double(point.getX()).intValue();
                ys[i] = new Double(point.getY()).intValue();
            }
            g.fillPolygon(new Polygon(xs, ys, pontos.size()));
            g.setColor(Color.BLUE);
            g.drawString("Fernando", (xs[0]+xs[1])/2+5, (ys[0]+ys[1])/2+5);
            pontos.clear();
        }
    }

    private void desenhaLinhas() {
        if (pontos.size() > 1) {
            Graphics g = this.getGraphics();
            Point ant = pontos.get(pontos.size() - 1);
            Point point = pontos.get(pontos.size() - 2);
            g.drawLine(point.x, point.y, ant.x, ant.y);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exercício 3 - Desenho com o mouse. - Fernando");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(692, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-769)/2, (screenSize.height-549)/2, 769, 549);
    }// </editor-fold>//GEN-END:initComponents

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    Graphics g = this.getGraphics();
    g.drawRoundRect(evt.getX(), evt.getY(), 2, 2, 0, 0);
    
    if (pontos.size()>0 && Math.abs(pontos.get(0).x-evt.getX())<10
            && Math.abs(pontos.get(0).y-evt.getY())<10) {
        desenhaQuadrado();
    } else {
        pontos.add(evt.getPoint());
        desenhaLinhas();
    }


}//GEN-LAST:event_formMouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.getGraphics().clearRect(0, 0, getWidth(), getHeight());
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDesenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDesenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDesenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDesenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JDesenho().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
