
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Teste.java
 *
 * Created on 26/03/2011, 23:25:53
 */
/**
 *
 * @author rudieri
 */
public class Teste extends javax.swing.JFrame {

    private ArrayList<String> list = new ArrayList<String>();
    private Java2sAutoTextField autoTextField;
    // private JTextArea textArea;
    DicaDeTexto dicaDeTexto;

    /** Creates new form Teste */
    public Teste() {
        initComponents();
        list.add("Rudieri");
        list.add("Turchiello");
        list.add("Colbek");
        list.add("Netbeans");
        list.add("WTF?");
        list.add("Testing");
        list.add("Setenta");
        list.add("Com espaço");
        list.add("SemEspaço");
        list.add("What?");
        dicaDeTexto = new DicaDeTexto(this.getContentPane());

    }

    public void adivinha() {
        String original = "";
        for (String string : list) {
            int inicioPalavra = 0;
            int fimPalavra = 0;
            inicioPalavra = jTextField1.getCaretPosition();

            String palavra = jTextField1.getText();
            original = palavra.substring(0, inicioPalavra);
            if (original.equals("")) {
                jTextField1.setText("");
                return;
            }

            if (string.toLowerCase().startsWith(original.toLowerCase())) {
                fimPalavra = palavra.length();
                jTextField1.setText(string);
                jTextField1.select(inicioPalavra, fimPalavra);
                jTextField1.setCaretPosition(inicioPalavra);
                return;
            }
        }
        jTextField1.setText(original);
    }

    private void fazerAlgo(JTextField source, KeyEvent evt){
         int cd = evt.getKeyCode();
        if ((cd < 48 || cd > 95) && cd != KeyEvent.VK_BACK_SPACE && cd != KeyEvent.VK_DELETE) {
            return;
        }
        ArrayList<String> lista = new ArrayList<String>();
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).toLowerCase().startsWith(source.getText().toLowerCase())) {
                lista.add(list.get(i));
            }
        }
        dicaDeTexto.paintBox(source, lista);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jTextField1.setPreferredSize(new java.awt.Dimension(240, 28));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);

        jTextField2.setPreferredSize(new java.awt.Dimension(240, 28));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel4);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-402)/2, (screenSize.height-242)/2, 402, 242);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
      fazerAlgo(jTextField1, evt);

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        fazerAlgo(jTextField2, evt);
    }//GEN-LAST:event_jTextField2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teste().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
