/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPreferencias.java
 *
 * Created on 19/03/2011, 11:43:17
 */
package jogovelha.tela;

import jogovelha.Loader;
import jogovelha.tabuleiro.Tabuleiro;
import jogovelha.utils.MyComboBoxModel;

/**
 *
 * @author rudieri
 */
public class JPreferencias extends javax.swing.JDialog {

    private TelaVelha telaVelha;
    private MyComboBoxModel aiModel;

    /** Creates new form JPreferencias */
    public JPreferencias(TelaVelha parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.telaVelha = parent;
        aiModel = new MyComboBoxModel();
        aiModel.addElementIfNotExist(Loader.pacotePadrao + "Jogador2");
        aiModel.addElementIfNotExist(Loader.pacotePadrao + "RJogador");
        jComboBox_AiComputador.setModel(aiModel);
    }

    @Override
    public void setVisible(boolean b) {

        if (b) {
            if (telaVelha.quemComeca == Tabuleiro.JOGADOR_HUMANO) {
                jComboBox_Jogador.setSelectedItem("Humano");
            } else {
                jComboBox_Jogador.setSelectedItem("Computador");
            }
            short index = aiModel.getIndexOfElement(telaVelha.getNomeDoMeuAdversario());
            if (index == -1) {
                jComboBox_AiComputador.setSelectedItem(telaVelha.getNomeDoMeuAdversario());
            } else {
                jComboBox_AiComputador.setSelectedIndex(index);
            }
        }
        super.setVisible(b);
    }

    private void salvarJogadorComeca() {
        if (((String) jComboBox_Jogador.getSelectedItem()).equalsIgnoreCase("humano")) {
            telaVelha.quemComeca = Tabuleiro.JOGADOR_HUMANO;
        } else {
            telaVelha.quemComeca = Tabuleiro.JOGADOR_COMPUTADOR;
        }
    }

    private void salvarAiJogador() {
        String jogador = (String) jComboBox_AiComputador.getSelectedItem();
        aiModel.addElementIfNotExist(jogador);
        telaVelha.alterarAiJogador(jogador);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Jogador = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_AiComputador = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton_Fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

        jLabel1.setText("Quem começa o jogo: ");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 18));
        jPanel1.add(jLabel1);

        jComboBox_Jogador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Humano", "Computador" }));
        jComboBox_Jogador.setPreferredSize(new java.awt.Dimension(180, 28));
        jComboBox_Jogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_JogadorActionPerformed(evt);
            }
        });
        jComboBox_Jogador.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox_JogadorPropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox_Jogador);

        getContentPane().add(jPanel1);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));

        jLabel2.setText("AI do Computador:");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 18));
        jPanel3.add(jLabel2);

        jComboBox_AiComputador.setEditable(true);
        jComboBox_AiComputador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jogador2", "RJogador" }));
        jComboBox_AiComputador.setPreferredSize(new java.awt.Dimension(180, 28));
        jComboBox_AiComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AiComputadorActionPerformed(evt);
            }
        });
        jComboBox_AiComputador.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox_AiComputadorPropertyChange(evt);
            }
        });
        jPanel3.add(jComboBox_AiComputador);

        getContentPane().add(jPanel3);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton_Fechar.setText("Fechar");
        jButton_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FecharActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Fechar);

        getContentPane().add(jPanel2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-395)/2, (screenSize.height-129)/2, 395, 129);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_JogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_JogadorActionPerformed
        // TODO add your handling code here:
        //        telaVelha.quemComeca
    }//GEN-LAST:event_jComboBox_JogadorActionPerformed

    private void jComboBox_JogadorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox_JogadorPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_JogadorPropertyChange

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FecharActionPerformed
        // TODO add your handling code here:
        salvarJogadorComeca();
        dispose();
    }//GEN-LAST:event_jButton_FecharActionPerformed

    private void jComboBox_AiComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AiComputadorActionPerformed
        // TODO add your handling code here:
        salvarAiJogador();
//        dispose();
    }//GEN-LAST:event_jComboBox_AiComputadorActionPerformed

    private void jComboBox_AiComputadorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox_AiComputadorPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AiComputadorPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Fechar;
    private javax.swing.JComboBox jComboBox_AiComputador;
    private javax.swing.JComboBox jComboBox_Jogador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
