package jogovelha.tela;

import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jogovelha.ai.Jogador;
import jogovelha.marcacao.Marca;
import jogovelha.marcacao.Ponto;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaVelha.java
 *
 * Created on 05/03/2011, 08:58:22
 */
/**
 *
 * @author rudieri
 */
public class TelaVelha extends javax.swing.JDialog {

    private ImageIcon xis;
    private ImageIcon bolinha;
    private Marca pxis;
    private Marca pbol;
    public static final int JOGADOR_HUMANO = -1;
    public static final int JOGADOR_COMPUTADOR = 1;
    private int jogador;
    Jogador pc;

    /** Creates new form TelaVelha */
    public TelaVelha(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        BufferedImage fbx = ImageIO.read(getClass().getResource("../bitmaps/xis.png"));
        BufferedImage fbb = ImageIO.read(getClass().getResource("../bitmaps/bolinha.png"));
        int w = jTable1.getCellRect(0, 0, false).width;
        int h = jTable1.getCellRect(0, 0, false).height;
        xis = new ImageIcon(fbx.getScaledInstance(w, h, BufferedImage.SCALE_SMOOTH));
        bolinha = new ImageIcon(fbb.getScaledInstance(w, h, BufferedImage.SCALE_SMOOTH));
        jTable1.setDefaultRenderer(Object.class, new Render());
        pxis = new Marca(xis);
        pbol = new Marca(bolinha);
        jogador = JOGADOR_HUMANO;
       pc =  new Jogador(this);
    }

    public boolean jogar(int jogador, int linha, int coluna) {
        if (!estaLivre(linha, coluna)) {
            return false;
        }
        if (jogador == this.jogador) {
            if (jogador == JOGADOR_HUMANO) {
                setValue(pbol, linha, coluna);
                this.jogador = JOGADOR_COMPUTADOR;

                pc.inimigoMarcou(new Ponto((byte)linha, (byte)coluna));
            } else {
                setValue(pxis, linha, coluna);
                this.jogador = JOGADOR_HUMANO;
            }
        }
        return true;
    }

    public void setValue(Marca v, int linha, int coluna) {
        jTable1.setValueAt(v, linha, coluna);
    }

    public boolean estaLivre(int linha, int coluna) {
        return jTable1.getValueAt(linha, coluna) == null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(48);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-242)/2, (screenSize.height-192)/2, 242, 192);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        jogar(JOGADOR_HUMANO, row, col);

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    TelaVelha dialog = new TelaVelha(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Não foi possível carregar as imagens!!!");
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
