package jogovelha.tela;

import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import jogovelha.marcacao.Marca;
import jogovelha.marcacao.Mensageiro;
import jogovelha.tabuleiro.Tabuleiro;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaVelha.java
 *
 * Created on 05/03/2011, 08:58:22
 */
/**
 *
 * @author rudieri
 */
public class TelaVelha extends javax.swing.JDialog {

    private ImageIcon xis;
    private ImageIcon bolinha;
    private Marca pxis;
    private Marca pbol;
    private Tabuleiro tabuleiroReal;
    public byte quemComeca = Tabuleiro.JOGADOR_COMPUTADOR;
    private Mensageiro elFin;

    /** Creates new form TelaVelha */
    public TelaVelha(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        init();
//        pack();
    }

    private void init() throws IOException {
        initComponents();
        BufferedImage fbx = ImageIO.read(getClass().getResource("../bitmaps/xis.png"));
        BufferedImage fbb = ImageIO.read(getClass().getResource("../bitmaps/bolinha.png"));
        int w = jTable1.getCellRect(0, 0, false).width;
        int h = jTable1.getCellRect(0, 0, false).height;
        xis = new ImageIcon(fbx.getScaledInstance(w, h, BufferedImage.SCALE_SMOOTH));
        bolinha = new ImageIcon(fbb.getScaledInstance(w, h, BufferedImage.SCALE_SMOOTH));
        jTable1.setDefaultRenderer(Object.class, new Render());
        jTable1.setIgnoreRepaint(true);
        pxis = new Marca(xis);
        pbol = new Marca(bolinha);
        //tabuleiroReal.setTelaVelha(this);

    }

    private void limpar() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getColumnCount(); j++) {
                jTable1.setValueAt(null, i, j);
            }

        }
    }

    public void setTabuleiroReal(Tabuleiro tabuleiroReal) {
        this.tabuleiroReal = tabuleiroReal;
    }

    public void gameOver(Mensageiro _elFin) {

        this.elFin = _elFin;
        new Thread(new Runnable() {

            public void run() {
                try {
                    Rectangle cellRect = jTable1.getCellRect(elFin.cell1.linha, elFin.cell1.coluna, true);
                    Rectangle cellRectF = jTable1.getCellRect(elFin.cell3.linha, elFin.cell3.coluna, true);
                    Thread.sleep(50);
                    pintarLinha(cellRect, cellRectF, elFin.getDirecao());
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaVelha.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();

    }

    private void pintarLinha(Rectangle rectI, Rectangle rectF, int direcao) {
        int x1;
        int y1;
        int x2;
        int y2;
        switch (direcao) {
            case Mensageiro.HORIZONTAL:
                y1 = rectI.y + rectI.height / 2;
                x1 = rectI.x;
                x2 = rectF.x + rectF.width;
                y2 = y1;
                break;
            case Mensageiro.VERTICAL:
                x1 = rectI.x + rectI.width / 2;
                y1 = rectI.y;
                y2 = rectF.y + rectF.height;
                x2 = x1;
                break;
            case Mensageiro.DIAGONAL_PRINCIPAL:
                x1 = 0;
                y1 = 0;
                y2 = rectF.y + rectF.height;
                x2 = rectF.x + rectF.width;
                break;
            case Mensageiro.DIAGONAL_SECUNDARIA:
                x1 = rectI.x + rectI.width;
                y1 = 0;
                y2 = rectF.y + rectF.height;
                x2 = 0;
                break;
            default:
                throw new AssertionError();
        }
        jTable1.setIgnoreRepaint(true);
        jTable1.getGraphics().drawLine(x1, y1, x2, y2);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Status = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Jogo = new javax.swing.JMenu();
        jMenuItem_NovoJogo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Preferencias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(220, 150));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setPreferredSize(new java.awt.Dimension(220, 150));
        jTable1.setRowHeight(50);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 1));

        jLabel_Status.setText("...");
        jLabel_Status.setOpaque(true);
        jPanel1.add(jLabel_Status);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jMenu_Jogo.setMnemonic('j');
        jMenu_Jogo.setText("Jogo");

        jMenuItem_NovoJogo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem_NovoJogo.setText("Novo Jogo");
        jMenuItem_NovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NovoJogoActionPerformed(evt);
            }
        });
        jMenu_Jogo.add(jMenuItem_NovoJogo);

        jMenuBar1.add(jMenu_Jogo);

        jMenu2.setMnemonic('e');
        jMenu2.setText("Editar");

        jMenuItem_Preferencias.setText("Preferências");
        jMenuItem_Preferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PreferenciasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Preferencias);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-224)/2, (screenSize.height-220)/2, 224, 220);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.rowAtPoint(evt.getPoint());
        int col = jTable1.columnAtPoint(evt.getPoint());
        tabuleiroReal.jogar(Tabuleiro.JOGADOR_HUMANO, (byte)row, (byte)col);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem_NovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NovoJogoActionPerformed
        // TODO add your handling code here:
        limpar();
        tabuleiroReal.start(quemComeca);
    }//GEN-LAST:event_jMenuItem_NovoJogoActionPerformed

    private void jMenuItem_PreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PreferenciasActionPerformed
        // TODO add your handling code here:
        new JPreferencias(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem_PreferenciasActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        if (elFin!=null) {
            gameOver(elFin);
        }
    }//GEN-LAST:event_jTable1FocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
         if (elFin!=null) {
            gameOver(elFin);
        }
    }//GEN-LAST:event_formFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_NovoJogo;
    private javax.swing.JMenuItem jMenuItem_Preferencias;
    private javax.swing.JMenu jMenu_Jogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void setValor(int jogador, int linha, int coluna) {
        if (jogador == Tabuleiro.JOGADOR_COMPUTADOR) {
            jTable1.setValueAt(pxis, linha, coluna);
        } else {
            jTable1.setValueAt(pbol, linha, coluna);
        }
    }
}
