
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteTabela.java
 *
 * Created on 03/04/2011, 00:28:58
 */
/**
 *
 * @author rudieri
 */
public class TesteTabela extends javax.swing.JFrame {

    private long time;
    private boolean contando;

    /** Creates new form TesteTabela */
    public TesteTabela() {
        initComponents();
        ArrayList list = new ArrayList(1000);
        dorme1();
        startTimer();
        ModelOfTable modelOfTable = new ModelOfTable(500001);
//        DefaultTableModel modelOfTable = new DefaultTableModel();
        modelOfTable.addColumn("teste");
        modelOfTable.addColumn("666");
        for (int i = 0; i < 500000; i++) {
            Object[] row = new Object[2];
            row[0] = i;
            row[1] = i;
            modelOfTable.addRowFast(row);
//            modelOfTable.addRow(row);
        }
        jTable1.setModel(modelOfTable);
        System.out.println("Tempo: " + stopTimer() + "ms");
    }

    private void startTimer() {
        contando = true;
        time = new Date().getTime();
    }

    private void dorme1() {
        try {
            System.out.println("Esperando...");
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(TesteTabela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private long stopTimer() {
        if (contando) {
            contando = false;
            return new Date().getTime() - time;
        } else {
            return -1;
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TesteTabela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
