/* Generated By:JavaCC: Do not edit this line. JMenosConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JMenosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AC = 1;
  /** RegularExpression Id. */
  int DC = 2;
  /** RegularExpression Id. */
  int CLASS = 3;
  /** RegularExpression Id. */
  int METHOD = 4;
  /** RegularExpression Id. */
  int MAE = 5;
  /** RegularExpression Id. */
  int IMPRIME = 6;
  /** RegularExpression Id. */
  int LER = 7;
  /** RegularExpression Id. */
  int TEXTO = 8;
  /** RegularExpression Id. */
  int SPACE = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\"$\"",
    "\"#\"",
    "\"mae\"",
    "<IMPRIME>",
    "\"ler\"",
    "<TEXTO>",
    "<SPACE>",
    "\"\\t\"",
    "\"\\n\"",
  };

}
