/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import android.graphics.Bitmap;
import com.utils.BitmapDataObject;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author manchini
 */
public class JTelaLog extends javax.swing.JFrame {

    private Socket echoSocket;

    /**
     * Creates new form JTelaLOg
     */
    public JTelaLog() {
        initComponents();
    }

    private void conectar() {
        if (echoSocket == null) { // Conecta
            try {
                jButton1.setText("Desconecta");
                echoSocket = new Socket(jTextField_IP.getText(), new Integer(jTextField_Porta.getText()));
                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        while (echoSocket != null) {
                            try {
                                ObjectInputStream inp = new ObjectInputStream(echoSocket.getInputStream());
                                Object obj = inp.readObject();
                                if (obj instanceof BitmapDataObject) {
                                    BitmapDataObject bitmap = (BitmapDataObject) obj;


                                    OutputStream out = new FileOutputStream(new File("teste.jpg"));
                                    out.write(bitmap.imageByteArray, 0, bitmap.tamanho);

                                    Graphics2D graphics = (Graphics2D) jPanel_Img.getGraphics();
                                    Image img1 = Toolkit.getDefaultToolkit().getImage("teste.jpg");
                                    graphics.setColor(Color.WHITE);
                                    graphics.fillRect(0, 0, jPanel_Img.getWidth(), jPanel_Img.getHeight());
                                    graphics.translate(179, 0);
                                    graphics.rotate(Math.toRadians(90.0));
                                    graphics.drawImage(img1, 0, -img1.getWidth(null), null);
                                } else {
                                    jTextPane1.setText(jTextPane1.getText() + "\n" + obj.toString());
                                }
//                                inp.close();
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                    }
                }).start();


            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro", "Erro Fataliti ao Conectar", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            try {
                // se conectado Desconencta
                echoSocket.close();
                echoSocket = null;
                jButton1.setText("Conecta");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro", "Erro Fataliti ao Desconenctar", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_IP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Porta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel_Img = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente Log");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("IP:");
        jPanel2.add(jLabel1);

        jTextField_IP.setPreferredSize(new java.awt.Dimension(150, 28));
        jPanel2.add(jTextField_IP);

        jLabel2.setText("Porta:");
        jPanel2.add(jLabel2);

        jTextField_Porta.setText("6666");
        jTextField_Porta.setPreferredSize(new java.awt.Dimension(50, 28));
        jPanel2.add(jTextField_Porta);

        jButton1.setText("Conencta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout jPanel_ImgLayout = new javax.swing.GroupLayout(jPanel_Img);
        jPanel_Img.setLayout(jPanel_ImgLayout);
        jPanel_ImgLayout.setHorizontalGroup(
            jPanel_ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        jPanel_ImgLayout.setVerticalGroup(
            jPanel_ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_Img, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-944)/2, (screenSize.height-486)/2, 944, 486);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conectar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTelaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTelaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTelaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTelaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JTelaLog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_IP;
    private javax.swing.JTextField jTextField_Porta;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
