/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JCapas.java
 *
 * Created on 04/04/2011, 10:15:54
 */
package sistema3camadascliente.telas;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import sistema3camadasbase.musica.capas.Capa;
import sistema3camadasbase.util.FileUtils;

/**
 *
 * @author rudieri
 */
public class JCapas extends javax.swing.JDialog {

    private Capa capa;
    final static String diretorio = "miniaturas/";

    /** Creates new form JCapas */
    public JCapas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private String salvarMiniatura(BufferedImage icon) {
        String nome = "teste.jpg";
        File teste = new File(nome);
        
        FileUtils.gravaArquivoImagem(icon, teste);
        return nome;

    }

    public Capa selecionarCapa(){
        setVisible(true);
        return capa;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Selecione outra imagem...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fil = new JFileChooser();

        fil.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.getName().indexOf(".jpg") != -1;
            }

            @Override
            public String getDescription() {
                return "nothing";
            }
        });
        if (JFileChooser.APPROVE_OPTION == fil.showOpenDialog(this)) {

            BufferedImage read = FileUtils.leArquivoImagem(fil.getSelectedFile());
            Graphics g = read.getGraphics();
            ImageIcon imageIcon = new ImageIcon(read.getScaledInstance(100, 100, BufferedImage.SCALE_SMOOTH));
            g.drawImage(read, 0, 0, null);
            String nome = salvarMiniatura(read);
            capa = new Capa();
            capa.setNome(nome);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JCapas dialog = new JCapas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
