/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JConfiguracao.java
 *
 * Created on 19/08/2010, 21:17:54
 */
package com.crepz.config;

import com.crepz.config.constantes.TelaPadrao;
import com.crepz.log.NivelLog;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

/**
 *
 * @author manchini
 */
public class JConfiguracao extends javax.swing.JDialog {

    private JFileChooser jFileChooserPastaArquivos = new JFileChooser();

    /**
     * Creates new form JConfiguracao
     */
    public JConfiguracao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTela();
    }

    public JConfiguracao(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();


        setTela();

    }

    private void setTela() {
        try {
            // restringe a amostra a diretorios apenas

            

            jSpinnerTempo.setValue(Configuracaoes.getInteger(Configuracaoes.CONF_TEMPO_SALVAR_ARQUIVOS));
            jFileChooserPastaArquivos.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jFileChooserPastaArquivos.setMultiSelectionEnabled(false);
            jFileChooserPastaArquivos.setDialogTitle("Abrir Pasta");
            jComboBoxTelaPadrao.setModel(new DefaultComboBoxModel(TelaPadrao.getNomesFakes()));
            jComboBoxTelaPadrao.setSelectedIndex(Configuracaoes.getEnum(Configuracaoes.CONF_TELA_PADRAO).ordinal());
            jTextField_Pasta1.setText(Configuracaoes.getString(Configuracaoes.CONF_PASTA_SALVAR));
            jComboBoxNivelLog.setModel(new DefaultComboBoxModel(NivelLog.getNomesFakes()));
            jComboBoxNivelLog.setSelectedIndex(Configuracaoes.getEnum(Configuracaoes.CONF_NIVEL_LOG).ordinal());
            //java -classpath /home/rudieri/NetBeansProjects/CrepzPlayer/build/classes/ com.hotkey.linux.DisparaComando --prev
//            String local = getClass().getResource("/").getFile();
//            jTextFieldPlay.setText("java -classpath " + local + " com.hotkey.linux.DisparaComando --play");
//            jTextFieldNext.setText("java -classpath " + local + " com.hotkey.linux.DisparaComando --next");
//            jTextFieldPrev.setText("java -classpath " + local + " com.hotkey.linux.DisparaComando --prev");
//            jTextFieldStop.setText("java -classpath " + local + " com.hotkey.linux.DisparaComando --stop");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Geral = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTelaPadrao = new javax.swing.JComboBox();
        jPanel20 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Pasta1 = new javax.swing.JTextField();
        jButtonProcurar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerTempo = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxNivelLog = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(441, 342));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 25));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel2.setText("Configurações");
        jPanel4.add(jLabel2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel_Geral.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.BorderLayout());
        jPanel_Geral.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Tela Inicial ao Abrir o Crepz:");
        jLabel9.setPreferredSize(new java.awt.Dimension(165, 13));
        jPanel15.add(jLabel9);

        jComboBoxTelaPadrao.setToolTipText("O que acontece quando eu clido 2 vezes numa música...");
        jPanel15.add(jComboBoxTelaPadrao);

        jPanel1.add(jPanel15);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setText("Pasta para salvar Arquivos:");
        jLabel11.setPreferredSize(new java.awt.Dimension(165, 18));
        jPanel20.add(jLabel11);

        jTextField_Pasta1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel20.add(jTextField_Pasta1);

        jButtonProcurar.setMnemonic('P');
        jButtonProcurar.setText("Procurar...");
        jButtonProcurar.setToolTipText("Abre uma tela para você escolher uma pasta... (Alt + P)");
        jButtonProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarActionPerformed(evt);
            }
        });
        jPanel20.add(jButtonProcurar);

        jPanel1.add(jPanel20);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Tamanho dos Arquivos:");
        jLabel1.setPreferredSize(new java.awt.Dimension(165, 16));
        jPanel2.add(jLabel1);

        jSpinnerTempo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 120, 5));
        jPanel2.add(jSpinnerTempo);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setText("Minutos");
        jLabel3.setPreferredSize(new java.awt.Dimension(165, 16));
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setText("Nível Mínimo do Log:");
        jLabel10.setPreferredSize(new java.awt.Dimension(165, 13));
        jPanel17.add(jLabel10);

        jComboBoxNivelLog.setToolTipText("O que acontece quando eu clido 2 vezes numa música...");
        jPanel17.add(jComboBoxNivelLog);

        jPanel1.add(jPanel17);

        jPanel_Geral.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Geral", jPanel_Geral);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 35));

        jButtonSalvar.setMnemonic('S');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar configurações. (Alt + S )");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonSalvar);

        jButtonFechar.setMnemonic('C');
        jButtonFechar.setText("Cancelar");
        jButtonFechar.setToolTipText("Cancelar. (Alt + C)");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonFechar);

        getContentPane().add(jPanel11, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(706, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        setDadosBanco();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        Configuracaoes.set(Configuracaoes.CONF_TELA_PADRAO, TelaPadrao.values()[jComboBoxTelaPadrao.getSelectedIndex()]);
        Configuracaoes.set(Configuracaoes.CONF_PASTA_SALVAR, jTextField_Pasta1.getText());
        Configuracaoes.set(Configuracaoes.CONF_TEMPO_SALVAR_ARQUIVOS, (Integer)jSpinnerTempo.getValue());
        Configuracaoes.set(Configuracaoes.CONF_NIVEL_LOG, NivelLog.values()[jComboBoxNivelLog.getSelectedIndex()]);
        dispose();
//        setDadosBanco();

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarActionPerformed
        int showOpenDialog = jFileChooserPastaArquivos.showOpenDialog(this);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            jTextField_Pasta1.setText(jFileChooserPastaArquivos.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonProcurarActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonProcurar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxNivelLog;
    private javax.swing.JComboBox jComboBoxTelaPadrao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Geral;
    private javax.swing.JSpinner jSpinnerTempo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_Pasta1;
    // End of variables declaration//GEN-END:variables
}
