/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geomanalitica.math;

import java.awt.Component;
import javax.swing.AbstractCellEditor;
import javax.swing.CellEditor;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import com.geomanalitica.utils._3d.Ponto3D;
import com.geomanalitica.utils._3d.Vetor3D;

/**
 *
 * @author rudieri
 */
public class JMath extends javax.swing.JFrame {

    /**
     * Creates new form JMath
     */
    public JMath() {
        initComponents();
        inicializaTabela();
    }
    
    private void inicializaTabela(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Valor1");
        model.addColumn("Operação");
        model.addColumn("Valor2");
        model.addColumn("Resultado");
        jTable1.setModel(model);
        jTable1.setDefaultEditor(Object.class, new MyTableEditor());
        
        model.addRow(new Object[]{new Vetor3D(0, 0, 0),new Vetor3D(0, 0, 0),new Vetor3D(0, 0, 0),new Vetor3D(0, 0, 0)});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JMath().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

private class MyTableEditor extends AbstractCellEditor implements TableCellEditor{

        JTextField jTextField = new JTextField();
        JLabel jLabel = new JLabel();
        Object current;
        @Override
        public Object getCellEditorValue() {
            if (current==null) {
                return null;
            }
            if (current instanceof Vetor3D) {
                String[] obj = jTextField.getText().replace("[", "").replace("]", "").replace(" ", "").split(",", 3);
                if (obj.length==3) {
                    return new Vetor3D(Double.valueOf(obj[0]), Double.valueOf(obj[1]), Double.valueOf(obj[2]));
                }
                return null;
            }else if(current instanceof Ponto3D){
                String[] obj = jTextField.getText().replaceAll("[^,-9] ", "").split(",", 3);
                if (obj.length==3) {
                    return new Ponto3D(Double.valueOf(obj[0]), Double.valueOf(obj[1]), Double.valueOf(obj[2]));
                }
                return null;
            }
            return current;
        }

        @Override
        public Component getTableCellEditorComponent(JTable jtable, Object o, boolean bln, int i, int i1) {
            current = o;
            if (o ==null ) {
                jLabel.setText("");
                return jLabel;
            }
            if (o instanceof Vetor3D) {
                jTextField.setText(o.toString());
                return jTextField;
            }else if( o instanceof Ponto3D ){
                jTextField.setText(o.toString());
                return jTextField;
            }
            jLabel.setText(o.toString());
            return jLabel;
        }
        
        
    
}

}
